[package]
name = "paldex-sav"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
oozextract = "0.5"
flate2 = "1"
thiserror.workspace = true

[dev-dependencies]
paldex-locate.workspace = true

[lints]
workspace = true
