[package]
name = "paldex-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
paldex-model.workspace = true
paldex-gvas.workspace = true
paldex-sav.workspace = true
paldex-locate.workspace = true
uuid.workspace = true
thiserror.workspace = true
rusqlite = { version = "0.32", features = ["bundled"] }
notify = "8"
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
