[package]
name = "paldex-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
png.workspace = true
repak-oodle.workspace = true
thiserror.workspace = true

[dev-dependencies]
paldex-gvas.workspace = true
paldex-locate.workspace = true
paldex-model.workspace = true
paldex-sav.workspace = true

[lints]
workspace = true
