//! The stable interface the rest of the app depends on for species names,
//! passive-skill definitions, breeding results, and icon artwork — deliberately
//! decoupled from *how* that data was obtained, per the plan's Phase 3 design:
//! "the UI depends only on this trait, so swapping the fallback in is a
//! one-line change."
//!
//! ## Everything here comes from the user's own pak
//!
//! [`crate::ReferenceIndex`] is the real implementation, built from the
//! installed game. Three mechanisms cover it, and the third only became
//! possible once a `.usmap` existed.
//!
//! ### The constraint
//!
//! Palworld's `DataTable` packages are cooked with
//! `PKG_UnversionedProperties` set — confirmed by reading the flag directly
//! off the real `DT_PalMonsterParameter.uasset`
//! (`PackageFlags = 0x80002200`), and corroborated by its name table
//! containing no field names at all (no `HP`, no `ZukanIndex`). Unversioned
//! rows identify their properties positionally against the compiled class
//! schema, so deserializing them needs a `.usmap` mapping file, and none
//! ships in the pak (checked: zero `.usmap` entries in all 185,003).
//!
//! ### Schema-free data
//!
//! Two kinds of data escape that constraint, because neither depends on the
//! row schema:
//!
//! - **Name tables** are plain `FString`s in every cooked package. This gives
//!   the full Pal species key set from `DT_PalMonsterParameter` and the human
//!   key set from `DT_PalHumanParameter` — which is what finally lets human
//!   NPCs be filtered out of the Pal roster, the classification Phase 2
//!   deferred to here.
//! - **Localized text** is stored as `FText`, three plain `FString`s
//!   (namespace, key, source), so [`crate::text_table`] reads it directly.
//!   Palworld's `Game.locres` files are empty; all text lives in per-language
//!   `DataTable`s. This yields real display names for species, skills,
//!   technologies, items, and map objects in all 17 shipped languages.
//!
//! Icons are also outside the constraint — see [`crate::texture`]. A cooked
//! texture writes its pixel format as a plain `FString`, which is enough to
//! locate `FTexturePlatformData` and its mips without a schema.
//!
//! ### Schema-bound data, now available
//!
//! [`Species::dex_number`], [`Species::elements`], [`Species::stats`],
//! [`Species::rarity`] and [`Species::work_suitabilities`] are read from
//! `DT_PalMonsterParameter` by [`crate::datatable`], against the
//! `Mappings.usmap` bundled with this crate and regenerated by
//! `tools/usmap/regen-usmap.sh`. Before that existed, the dex numbers came
//! from a vendored third-party table; the extracted values were verified to
//! reproduce it exactly — all 288 entries, numbers and variant suffixes, zero
//! disagreements — before it was deleted.
//!
//! Everything therefore comes from the user's own installation at runtime, so
//! no game assets are redistributed and the plan's pre-agreed fallback of
//! vendoring a third-party dataset ended up not being needed at all.
//!
//! Breeding results come from the same mechanism — `DT_PalCombiUnique` for the
//! authored exceptions, and the generic `CombiRank` rule for everything else.
//! See [`crate::breeding`], which also records the two in-game experiments that
//! settled the rank tie-break, since that rule is not in the pak at all.
//!
//! The enum names in [`Species::elements`] and [`Species::work_suitabilities`]
//! are internal (`Leaf`, `Earth`, `Handcraft`) and are not what the game shows.
//! [`crate::ReferenceIndex::element_name`] and
//! [`crate::ReferenceIndex::work_suitability_name`] translate them, using the
//! pak's own UI string table so the labels stay localized.
//!
//! [`PassthroughReferenceData`] is retained for tests and for the case where
//! no pak is available (the app must still run without the game installed).

/// A Pal species' base stats, as `DT_PalMonsterParameter` stores them.
///
/// These are the per-species multipliers the game combines with level, IVs and
/// souls — not a finished stat line.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct BaseStats {
    pub hp: u32,
    pub melee_attack: u32,
    pub shot_attack: u32,
    pub defense: u32,
    pub support: u32,
    pub craft_speed: u32,
}

/// A Pal species' static reference data.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Species {
    pub character_id: String,
    pub display_name: String,
    /// Paldeck number. `None` for tower bosses, raid/collab content, and
    /// unused entries, which the game data itself leaves unnumbered — that
    /// absence is what separates a real Paldeck species from the rest.
    pub dex_number: Option<u32>,
    /// Variant marker shown after the number, e.g. the `B` in `005B`. Empty
    /// for a base species.
    pub dex_suffix: String,
    /// Element types, in the game's order, with the `None` slot omitted — so
    /// one entry for a single-element species and two for a dual.
    pub elements: Vec<String>,
    /// Rarity tier as authored, which drives the in-game rarity stars.
    pub rarity: u32,
    pub stats: BaseStats,
    /// Work suitability levels, keyed by the game's own suitability name
    /// (`Handcraft`, `Mining`, …). Only levels above zero are present, so an
    /// absent key means the species cannot do that job at all.
    pub work_suitabilities: std::collections::BTreeMap<String, u32>,
}

impl Species {
    /// The Paldeck label as the game shows it, e.g. `005B`, or `None` for a
    /// species with no Paldeck entry.
    #[must_use]
    pub fn dex_label(&self) -> Option<String> {
        self.dex_number
            .map(|n| format!("{n:03}{}", self.dex_suffix))
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct PassiveSkill {
    pub id: String,
    pub display_name: String,
}

pub trait ReferenceData {
    fn species(&self, character_id: &str) -> Option<&Species>;
    fn passive(&self, id: &str) -> Option<&PassiveSkill>;
    fn breeding_result(&self, a: &str, b: &str) -> Option<&str>;

    /// The pak entry holding this species' icon, without its file extension.
    ///
    /// Deliberately a *path* rather than the plan's original
    /// `icon(&self) -> Option<&[u8]>`. Returning borrowed bytes would force
    /// every icon to be decoded and held up front — 424 textures, each a
    /// block-decompress plus a PNG encode — when a session typically views a
    /// handful. Callers pair this with [`crate::load_icon_png`] to decode on
    /// demand and cache.
    fn icon_path(&self, character_id: &str) -> Option<&str>;
}

/// A stub [`ReferenceData`] with no real data behind it — `species`/`passive`
/// echo the raw id back as the display name (so the UI has *something*
/// readable rather than a blank field) and never resolve dex numbers, icons,
/// or breeding results. Exists so the rest of the app can be built and
/// tested against the real trait shape before a real data source lands.
#[derive(Debug, Default)]
pub struct PassthroughReferenceData;

impl ReferenceData for PassthroughReferenceData {
    fn species(&self, _character_id: &str) -> Option<&Species> {
        None
    }

    fn passive(&self, _id: &str) -> Option<&PassiveSkill> {
        None
    }

    fn breeding_result(&self, _a: &str, _b: &str) -> Option<&str> {
        None
    }

    fn icon_path(&self, _character_id: &str) -> Option<&str> {
        None
    }
}
